### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by AlexGisi** [alantao912/juliette#21]
Hi Alan, since the readme suggests building on "Any UNIX derived OS", just wanted to point out a compilation error on macos (ventura 13.1):

```
src/util.h:140:16: error: definition of type 'stack_t' conflicts with typedef of the same name
typedef struct stack_t {
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_sigaltstack.h:48:33: note: 'stack_t' declared here
typedef _STRUCT_SIGALTSTACK     stack_t; /* [???] signal stack */
```

it seems some internal structure in the macos developer stack is also named `stack_t`. Would you consider wrapping in a namespace or renaming to support macos compilation?

**Comment by alantao912** [comment]
Fixed
